dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get github.com/mattn/goveralls

script:
  - golangci-lint run
  - go test -covermode=count -coverprofile=coverage.out -v ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci